### PR TITLE
Created ICM loading script for the SorinLab

### PR DESCRIPTION
**Pull request by Aingty**
I don't have to.

### CODE REVIEW

**Comment by khaister** [comment]
Hi Aingty, this script could be better in its own repository, e.g. `icm-utils`.

**Comment by xaviermartinez2012** [comment]
Good idea Khai! Maybe move over the other icm-type scripts in utils too?

-XM

**Comment by khaister** [comment]
Sure but I don't believe there are any ICM-related scripts in this repo currently.

**Comment by xaviermartinez2012** [comment]
That's right. My b

**Comment by Aingty** [comment]
I believe the only other ICM script is the docking script. But you are right, it is not in the repo. I'll add another ICM directory and put both script in there. 

Aingty E.

**Comment by khaister** [comment]
@Aingty: `docking-scripts` was maintained by @barracks510 and contains scripts for "docking". If the purpose of your script fits the context of this repo, you can add it to the repo. Otherwise, I'd recommend a brand new repo. It's ok to have a repo with only one script. I'd recommend adding a readme to clarify the intention/purpose of the script(s).

**Pull request closed without merging**
